- name : demo for creating loops
  hosts: all
  become: yes
  vars:
    users:
      - akbar
      - iqra
      - arhaan
      - aqsa
  tasks:
    - name: creating users
      users:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
