---
- name : Install httpd package on web servers
  hosts: webservers
  become: yes
  tasks:
    - name : install latest httpd package
      yum:
        name: httpd
        state: absent
    - name: stop httpd
      systemd:
        name: httpd
        state: stopped
      
