---
- name : Install httpd package on web servers
  hosts: webservers
  become: yes
  vars:
    package: nginx
  tasks:
    - name: stop nginx service
      service:
        name: "{{ package }}"
        state: stopped
    - name : gather services facts
      service_facts:
    - name: start nginx if down
      service:
        name: "{{ package }}"
        state: started
      when: ansible_facts.services['nginx.service'].state != running
